# -*- coding: utf-8 -*-
"""
@author: Alexandre Sac--Morane
alexandre.sac-morane@uclouvain.be

This file contains the different functions to write files used in the simulation.
"""

#-------------------------------------------------------------------------------
#Librairy
#-------------------------------------------------------------------------------

import math

#-------------------------------------------------------------------------------

def Write_grains_vtk(namefile, L_g):
    """
    Write grains configuration as a .vkt readable with Paraview.

        Input :
            a name of the file (a string)
            a list of grain (a list)
        Output :
            Nothing, but a .vtk file is generated (a file)
    """
    file_to_write = open(namefile, 'w')
    file_to_write.write('# vtk DataFile Version 4.1\n')
    file_to_write.write('Generated by DEM_OedometricTest_AcidInjection\n')
    file_to_write.write('ASCII\n')
    file_to_write.write('DATASET POLYDATA\n')

    #coordinates of points
    file_to_write.write('POINTS '+str(len(L_g))+' float\n')
    counter = 0
    for grain in L_g :
        file_to_write.write(str(grain.center[0])+' '+str(grain.center[1])+' '+str(grain.center[2]))
        counter = counter + 1
        if counter == 3:
            file_to_write.write('\n')
            counter = 0
        else :
            file_to_write.write(' ')
    if counter < 3 :
        file_to_write.write('\n')

    #vertices of points
    file_to_write.write('VERTICES '+str(len(L_g))+' '+str(2*len(L_g))+'\n')
    counter = 0
    for grain in L_g :
        file_to_write.write('1 '+str(counter)+'\n')
        counter = counter + 1

    file_to_write.write('\n')
    file_to_write.write('POINT_DATA '+str(len(L_g))+'\n')
    file_to_write.write('FIELD FieldData 4\n')

    #ids of point
    file_to_write.write('id 1 '+str(len(L_g))+' int\n')
    counter = 0
    for grain in L_g :
        file_to_write.write(str(grain.id))
        counter = counter + 1
        if counter == 9:
            file_to_write.write('\n')
            counter = 0
        else :
            file_to_write.write(' ')
    if counter < 9 :
        file_to_write.write('\n')

    #radius of point
    file_to_write.write('radius 1 '+str(len(L_g))+' double\n')
    counter = 0
    for grain in L_g :
        file_to_write.write(str(grain.radius))
        counter = counter + 1
        if counter == 9:
            file_to_write.write('\n')
            counter = 0
        else :
            file_to_write.write(' ')
    if counter < 9 :
        file_to_write.write('\n')

    #speeds of point
    file_to_write.write('v 3 '+str(len(L_g))+' double\n')
    counter = 0
    for grain in L_g :
        file_to_write.write(str(grain.v[0])+' '+str(grain.v[1])+' '+str(grain.v[2]))
        counter = counter + 1
        if counter == 3:
            file_to_write.write('\n')
            counter = 0
        else :
            file_to_write.write(' ')
    if counter < 3 :
        file_to_write.write('\n')

    #rotations of point
    file_to_write.write('omega 3 '+str(len(L_g))+' double\n')
    counter = 0
    for grain in L_g :
        file_to_write.write(str(grain.w[0])+' '+str(grain.w[1])+' '+str(grain.w[2]))
        counter = counter + 1
        if counter == 3:
            file_to_write.write('\n')
            counter = 0
        else :
            file_to_write.write(' ')
    if counter < 3 :
        file_to_write.write('\n')

    #close file
    file_to_write.close()

#-------------------------------------------------------------------------------

def Write_box_vtk(namefile, dict_sample):
    """
    Write box configuration as a .vkt readable with Paraview.

        Input :
            a name of the file (a string)
            a list of grain (a list)
        Output :
            Nothing, but a .vtk file is generated (a file)
    """
    file_to_write = open(namefile, 'w')
    file_to_write.write('# vtk DataFile Version 4.1\n')
    file_to_write.write('Generated by DEM_OedometricTest_AcidInjection\n')
    file_to_write.write('ASCII\n')
    file_to_write.write('DATASET POLYDATA\n')

    #coordinates of points
    file_to_write.write('POINTS 20 float\n')
    for i in range(10):
        theta = 2*math.pi*i/10
        x = dict_sample['D_oedo']/2*math.cos(theta)
        y = dict_sample['D_oedo']/2*math.sin(theta)
        file_to_write.write(str(x)+' '+str(y)+' '+str(dict_sample['z_box_min'])+'\n')
    for i in range(10):
        theta = 2*math.pi*i/10
        x = dict_sample['D_oedo']/2*math.cos(theta)
        y = dict_sample['D_oedo']/2*math.sin(theta)
        file_to_write.write(str(x)+' '+str(y)+' '+str(dict_sample['z_box_max'])+'\n')

    #define polygons
    file_to_write.write('POLYGONS 12 72\n')
    #lower wall
    file_to_write.write('10 0 1 2 3 4 5 6 7 8 9\n')
    #upper wall
    file_to_write.write('10 10 11 12 13 14 15 16 17 18 19\n')
    #lateral wall
    file_to_write.write('4 0 1 11 10\n')
    file_to_write.write('4 1 2 12 11\n')
    file_to_write.write('4 2 3 13 12\n')
    file_to_write.write('4 3 4 14 13\n')
    file_to_write.write('4 4 5 15 14\n')
    file_to_write.write('4 5 6 16 15\n')
    file_to_write.write('4 6 7 17 16\n')
    file_to_write.write('4 7 8 18 17\n')
    file_to_write.write('4 8 9 19 18\n')
    file_to_write.write('4 9 0 10 19\n')

    #close file
    file_to_write.close()
